Build application before release

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -5,20 +5,59 @@ on:
     types: [created]
 
 jobs:
-  release:
-    name: Release Binary
+  executebuild:
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
+      - name: Run Application Build
+        id: build
+        run: |
+          response=$(curl -X POST -H "Accept: application/vnd.github.v3+json" \
+              -u ${{ secrets.GITHUB_TOKEN }} \
+              https://api.github.com/repos/${{ github.repository }}/actions/workflows/build.yml/dispatches \
+              -d '{"ref": "main"}')
+          run_id=$(curl -H "Accept: application/vnd.github+json" \
+              -u ${{ secrets.GITHUB_TOKEN }} \
+              https://api.github.com/repos/${{ github.repository }}/actions/runs \
+              | jq -r '.workflow_runs[] | select(.head_branch=="main") | .id' \
+              | head -n 1)
+          echo "run_id=$run_id" >> $GITHUB_ENV
+  waiting:
+    # status Can be one of: completed, action_required, cancelled, failure, neutral, skipped, stale, success, timed_out, in_progress, queued, requested, waiting, pending
+    # conclusion Can be one of: action_required, cancelled, failure, neutral, success, skipped, stale, timed_out
+    runs-on: ubuntu-latest
+    needs: executebuild
+    steps:
+      - name: Wait for Build Completion
+        run: |
+          while true; do
+            status=$(curl -H "Accept: application/vnd.github+json" \
+                -u ${{ secrets.GITHUB_TOKEN }} \
+                https://api.github.com/repos/${{ github.repository }}/actions/runs/$RUN_ID \
+                | jq -r .status)
+            conclusion=$(curl -H "Accept: application/vnd.github+json" \
+                -u ${{ secrets.GITHUB_TOKEN }} \
+                https://api.github.com/repos/${{ github.repository }}/actions/runs/$RUN_ID \
+                | jq -r .conclusion)
+            if [ "$status" == "completed" ]; then
+              if [ "$conclusion" == "success" ]; then
+                break
+              else
+                exit 1
+              fi
+            fi
+            sleep 30
+          done
+  release:
+    name: Release Binary
+    needs: [executebuild, waiting]
+    runs-on: ubuntu-latest
+    steps:
       - name: Download Build Artifact
         uses: actions/download-artifact@v4
         with:
           name: mondoowebapp
-      - name: Set up Go
-        uses: actions/setup-go@v5.2.0
-        with:
-          go-version: ${{ vars.GOVERSION }}
+          run-id: ${{ env.RUN_ID }}
+          github-token: ${{ secrets.GITHUB_TOKEN }}
       - name: Upload Binary to Release
         uses: softprops/action-gh-release@v1
         with:
